apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-deployment-drivers
spec:
  selector:
    matchLabels:
      app: myapp-drivers
  replicas: 3
  template:
    metadata:
      labels:
        app: myapp-drivers
    spec:
      containers:
      - name: myapp-drivers
        image: chrisloarryn/ts_api_drivers:latest
        ports:
        - containerPort: 4500
